# 🎵Data_Preparation🎵

In [763]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn.metrics as metrics 
import math
import warnings
import re 
warnings.filterwarnings("ignore", category=FutureWarning)
import pickle

In [764]:
df = pd.read_csv(r'C:\Users\Meital atar\Documents\DATA_SCIENCE\ML_PROJECT_spotify_songs\spotify_songs.csv', index_col=None) # without index

In [765]:
df.head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.0287,0.000009,0.2040,0.277,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.0803,0.000000,0.0833,0.725,123.976,189052

In [766]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

In [767]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
track_popularity,32833.0,42.477081,24.984074,0.000000,24.0000,45.000000,62.00000,100.000
danceability,32833.0,0.654850,0.145085,0.000000,0.5630,0.672000,0.76100,0.983
energy,32833.0,0.698619,0.180910,0.000175,0.5810,0.721000,0.84000,1.000
key,32833.0,5.374471,3.611657,0.000000,2.0000,6.000000,9.00000,11.000
loudness,32833.0,-6.719499,2.988436,-46.448000,-8.1710,-6.166000,-4.64500,1.275
mode,32833.0,0.565711,0.495671,0.000000,0.0000,1.000000,1.00000,1.000
speechiness,32833.0,0.107068,0.101314,0.000000,0.0410,0.062500,0.13200,0.918
acousticness,32833.0,0.175334,0.219633,0.000000,0.0151,0.080400,0.25500,0.994
instrumentalness,32833.0,0.084747,0.224230,0.000000,0.0000,0.000016,0.00483,0.994
liveness,32833.0,0.190176,0.154317,0.000000,0.0927,0.127000,0.24800,0.996
valence,32833.0,0.510561,0.233146,0.000000,0.3310,0.512000,0.69300,0.991
tempo,32833.0,120.881132,26.903624,0.000000,99.9600,121.984000,133.91800,239.440
duration_ms,32833.0,225799.811622,59834.006182,4000.000000,187819.0000,216000.000000,253585.00000,517810.000

### Change types

In [768]:
cols_to_convert = ['track_id', 'track_name', 'track_artist', 'track_album_id', 
                   'track_album_name', 'playlist_name', 'playlist_id', 
                   'playlist_genre', 'playlist_subgenre']

# Convert the columns to the 'string' type
df[cols_to_convert] = df[cols_to_convert].astype('string')

In [769]:
# Verify the change
print(df.dtypes)

track_id                    string[python]
track_name                  string[python]
track_artist                string[python]
track_popularity                     int64
track_album_id              string[python]
track_album_name            string[python]
track_album_release_date            object
playlist_name               string[python]
playlist_id                 string[python]
playlist_genre              string[python]
playlist_subgenre           string[python]
danceability                       float64
energy                             float64
key                                  int64
loudness                           float64
mode                                 int64
speechiness                        float64
acousticness                       float64
instrumentalness                   float64
liveness                           float64
valence                            float64
tempo                              float64
duration_ms                          int64
dtype: object

### Change type 'track_album_release_date'

In [770]:
df['track_album_release_date'] = pd.to_datetime(df['track_album_release_date'], errors='coerce')

# Verify the change
print(df['track_album_release_date'].dtypes)

datetime64[ns]

In [771]:
#df.info()
# now we finish to deal with types!

#Checking the data

In [772]:
df['track_id'].value_counts() #need to fix the data -> lowercase

track_id
7BKLCZ1jbUBVqRi2FVlTVw    10
3eekarcy7kvN4yt5ZFzltW     9
14sOS5L36385FJ3OL8hew4     9
0sf12qNH5qcw8qpgymFOqD     8
0nbXyq5TXYPCO7pr3N8S4I     8
                          ..
2jx9VNmPInE1d2m2T9eotT     1
0M2dqeUpxBGm8vujMTMhMV     1
22rdYlfxsz8QFXDIoA61Uu     1
4uVrL4P0nnH8QcRAQaCndD     1
29zWqhca3zt5NsckZqDf6c     1
Name: count, Length: 28356, dtype: Int64

In [773]:
df['track_name'].value_counts() #need to fix the data -> lowercase

track_name
Poison                                         22
Breathe                                        21
Alive                                          20
Forever                                        20
Stay                                           19
                                               ..
Get Up - Kosling Remix                          1
The Riddle - Steve Modana Radio Edit            1
Moonlight Shadow - The Cleric Remix             1
Bitter Sweet Symphony - Steve 80 Remix Edit     1
Typhoon - Original Mix                          1
Name: count, Length: 23449, dtype: Int64

In [774]:
df['track_artist'].value_counts()#need to fix the data -> lowercase

track_artist
Martin Garrix       161
Queen               136
The Chainsmokers    123
David Guetta        110
Don Omar            102
                   ...
Around The Way        1
Solomun               1
Mantronix             1
Shinehead             1
Mat Zo                1
Name: count, Length: 10692, dtype: Int64

In [775]:
df['track_popularity'].value_counts() #from 0 to 100

track_popularity
0      2703
1       575
57      541
60      514
51      514
       ...
97       22
95       15
96        7
99        4
100       2
Name: count, Length: 101, dtype: int64

In [776]:
df['track_album_id'].value_counts() #need to fix the data -> lowercase

track_album_id
5L1xcowSxwzFUSJzvyMp48    42
5fstCqs5NpIlF42VhPNv23    29
7CjJb2mikwAWA1V6kewFBF    28
4VFG1DOuTeDMBjBLZT7hCK    26
2HTbQ0RHwukKVXAlTmCZP2    21
                          ..
2qmihtU2XK0RlLLyEgpWtq     1
3RjznuaCdnYwdy3vdnE2Jh     1
23REtQMYdDesBrBEPfeqqp     1
5InOKiyUuh8tjJrHgWVWmn     1
0X3mUOm6MhxR7PzxG95rAo     1
Name: count, Length: 22545, dtype: Int64

In [777]:
df['track_album_name'].value_counts() #need to fix the data -> lowercase

track_album_name
Greatest Hits                               139
Ultimate Freestyle Mega Mix                  42
Gold                                         35
Malibu                                       30
Rock & Rios (Remastered)                     29
                                           ...
Exodus (アウトロ)                                 1
Playlist: The Very Best Of Bow Wow            1
J.Lo                                          1
Bad Boy 20th Anniversary Box Set Edition      1
Typhoon/Storm                                 1
Name: count, Length: 19743, dtype: Int64

In [778]:
df['track_album_release_date'].value_counts() # we allredy fix to datetime

track_album_release_date
2020-01-10    270
2019-11-22    244
2019-12-06    235
2019-12-13    220
2013-01-01    219
             ...
1979-01-05      1
1980-10-24      1
1978-03-03      1
1986-10-27      1
2014-04-18      1
Name: count, Length: 4453, dtype: int64

In [779]:
#Spotify was officially launched on October 7, 2008.

In [780]:

df['track_album_release_date'] = pd.to_datetime(df['track_album_release_date'], errors='coerce')

# Extract the year
df['track_album_release_date_year'] = df['track_album_release_date'].dt.year

# Filter tracks from 2008
df_filtered = df[(df['track_album_release_date_year'] >= 2008) ]

# Count unique track IDs
num_tracks = df_filtered['track_id'].nunique()

print(f"Number of unique track IDs from 2008 : {num_tracks}")

Number of unique track IDs from 2008 : 21207

The t-test results (T = -8.04, p ≈ 9.3e-16) provide compelling statistical evidence that the mean track popularity differs significantly between songs released prior to 2008 and those released in 2008 or later. Notably, songs released before 2008 exhibit a markedly lower average popularity score within this dataset. Given that these songs comprise 20% of the dataset and that the dataset is not particularly large, I decided to retain the data as is and not exclude songs released before 2008.

In [781]:
df['playlist_name'].value_counts() #need to fix the data -> lowercase

playlist_name
Indie Poptimism                                              308
2020 Hits & 2019  Hits – Top Global Tracks 🔥🔥🔥               247
Permanent Wave                                               244
Hard Rock Workout                                            219
Ultimate Indie Presents... Best Indie Tracks of the 2010s    198
                                                            ...
CSR 103:9 (GTA: SA)                                            7
Big White Room-Jessie-J                                        7
TOP 50 GLOBAL 2020 UPDATED WEEKLY 🌍🎶 WORLDWIDE                 6
ALPAS Music Festival                                           3
Post-Teen Pop                                                  1
Name: count, Length: 449, dtype: Int64

In [782]:
df['playlist_id'].value_counts() #need to fix the data -> lowercase

playlist_id
4JkkvMpVl4lSioqQjeAL0q    247
37i9dQZF1DWTHM4kX49UKs    198
6KnQDwp0syvhfHOR4lWP7x    195
3xMQTDLOIGvj3lWH5e5x6F    189
3Ho3iO0iJykgEQNbjB2sic    182
                         ...
4sr2xEhXQR5VuZ0LZX8TQ8      7
6dqoVI7qwYLyNqbg0MPad3      7
2CJsD3fcYJWcliEKnwmovU      6
6pPpLz42hUkr8gbMirkAEl      3
6HprqD6WZMx5peClrxaprN      1
Name: count, Length: 471, dtype: Int64

In [783]:
df['playlist_genre'].value_counts()

playlist_genre
edm      6043
rap      5746
pop      5507
r&b      5431
latin    5155
rock     4951
Name: count, dtype: Int64

In [784]:
df['playlist_subgenre'].value_counts() #need to remove special characters

playlist_subgenre
progressive electro house    1809
southern hip hop             1675
indie poptimism              1672
latin hip hop                1656
neo soul                     1637
pop edm                      1517
electro house                1511
hard rock                    1485
gangster rap                 1458
electropop                   1408
urban contemporary           1405
hip hop                      1322
dance pop                    1298
classic rock                 1296
trap                         1291
tropical                     1288
latin pop                    1262
hip pop                      1256
big room                     1206
new jack swing               1133
post-teen pop                1129
permanent wave               1105
album rock                   1065
reggaeton                     949
Name: count, dtype: Int64

In [785]:
df['danceability'].value_counts()

danceability
0.733    118
0.708    115
0.704    112
0.694    112
0.784    111
        ...
0.202      1
0.172      1
0.261      1
0.174      1
0.983      1
Name: count, Length: 822, dtype: int64

In [786]:
df['energy'].value_counts()

energy
0.7870    100
0.8280     99
0.8330     98
0.7950     91
0.7110     91
         ...
0.0671      1
0.0765      1
0.0455      1
0.0725      1
0.1060      1
Name: count, Length: 952, dtype: int64

In [787]:
df['key'].value_counts()

key
1     4010
0     3454
7     3352
9     3027
11    2996
2     2827
5     2680
6     2670
8     2430
10    2273
4     2201
3      913
Name: count, dtype: int64

In [788]:
df['mode'].value_counts()

mode
1    18574
0    14259
Name: count, dtype: int64

In [789]:
df['speechiness'].value_counts()

speechiness
0.1020    116
0.1030     98
0.1090     93
0.0354     93
0.1120     89
         ...
0.6000      1
0.6690      1
0.5840      1
0.5630      1
0.5780      1
Name: count, Length: 1270, dtype: int64

In [790]:
df['acousticness'].value_counts()

acousticness
0.102000    80
0.128000    80
0.101000    78
0.114000    74
0.141000    71
            ..
0.000075     1
0.000786     1
0.000086     1
0.000026     1
0.000434     1
Name: count, Length: 3731, dtype: int64

In [791]:
df['instrumentalness'].value_counts()

instrumentalness
0.000000    12089
0.001060       30
0.124000       30
0.000001       26
0.000001       26
            ...
0.000008        1
0.294000        1
0.003830        1
0.000089        1
0.008350        1
Name: count, Length: 4729, dtype: int64

In [792]:
df['liveness'].value_counts()

liveness
0.1110    346
0.1080    310
0.1100    305
0.1050    295
0.1040    294
         ...
0.0212      1
0.9610      1
0.9140      1
0.9350      1
0.7870      1
Name: count, Length: 1624, dtype: int64

In [793]:
df['valence'].value_counts()

valence
0.9610    69
0.5800    68
0.4300    68
0.5620    68
0.3890    68
          ..
0.0798     1
0.0576     1
0.0528     1
0.0698     1
0.0927     1
Name: count, Length: 1362, dtype: int64

In [794]:
df['tempo'].value_counts()

tempo
127.992    45
127.994    35
127.993    33
128.007    32
128.003    31
           ..
103.951     1
102.627     1
112.549     1
133.829     1
128.170     1
Name: count, Length: 17684, dtype: int64

In [795]:
df['duration_ms'].value_counts()

duration_ms
240000    37
192000    37
210000    30
180000    26
195000    25
          ..
185413     1
317760     1
220027     1
218505     1
367432     1
Name: count, Length: 19785, dtype: int64

In [796]:
#df.head() #Removal was successful

In [797]:
### loudness column

The loudness column represents the overall loudness of the track, measured in decibels (dB).
Typically, its values range from -60 to 0 dB, where values closer to 0 indicate higher loudness levels,
and values closer to -60 represent lower loudness levels. This column helps evaluate the dynamic range of the song.

In [798]:
df['loudness'].max()

1.275

In [799]:
df['loudness_log'] = df['loudness'].apply(lambda x: np.log1p(x) if x > 0 else x)

print(df[['loudness', 'loudness_log']].head())

   loudness  loudness_log
0    -2.634        -2.634
1    -4.969        -4.969
2    -3.432        -3.432
3    -3.778        -3.778
4    -4.672        -4.672

In [800]:
# Replace values in the 'loudness' column with 'loudness_log'
df['loudness'] = df['loudness_log']

# Drop the 'loudness_log' column from the DataFrame
df.drop(columns=['loudness_log'], inplace=True)

Since only a few songs (4) had loudness values exceeding the defined range (above 0), I opted to apply a logarithmic transformation rather than treating them as outliers.

## Changing the size of the letters to lowercase

In [801]:
cols_to_convert = ['track_id', 'track_artist', 'track_album_id', 'playlist_id','playlist_genre']

df[cols_to_convert] = df[cols_to_convert].apply(lambda x: x.str.lower())

In [802]:
df.head() #lowercase transform was successful

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,track_album_release_date_year
0,6f807x0ima9a1j3vpbc7vn,I Don't Care (with Justin Bieber) - Loud Luxur...,ed sheeran,66,2ocs0dgtsro98gh5zsl2cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dqzf1dxczdd7cfekhw,pop,...,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754,2019.0
1,0r7cvbztwzgbtcydfa2p31,Memories - Dillon Francis Remix,maroon 5,67,63rpso264urjw1x5e6cwv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dqzf1dxczdd7cfekhw,pop,...,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600,2019.0
2,1z1hg7vb0ahhdiemnde79l,All the Time - Don Diablo Remix,zara larsson,70,1hosmj2elcsrr0ve9gthr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dqzf1dxczdd7cfekhw,pop,...,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616,2019.0
3,75fpbthrwqmzhlbjlugdc7,Call You Mine - Keanu Silva Remix,the chainsmokers,60,1nqysoef1ykkugovchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dqzf1dxczdd7cfekhw,pop,...,-3.778,1,0.1020,0.0287,0.000009,0.2040,0.277,121.956,169093,2019.0
4,1e8pafckuyokkxphrhqw4x,Someone You Loved - Future Humans Remix,lewis capaldi,69,7m7vv9wlq4i0lfujie2zsq,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dqzf1dxczdd7cfekhw,pop,...,-4.672,1,0.0359,0.0803,0.000000,0.0833,0.725,123.976,189052,2019.0

## Special Character Removal

In [803]:
# Remove special characters from all columns with data type 'string'

In [804]:
# Identify all string-type columns
string_cols = df.select_dtypes(include=['string']).columns

# Remove special characters from all string columns
df[string_cols] = df[string_cols].apply(lambda x: x.str.replace(r'[^a-zA-Z0-9\s]', '', regex=True))

# Print cleaned DataFrame
print(df)

                     track_id  \
0      6f807x0ima9a1j3vpbc7vn
1      0r7cvbztwzgbtcydfa2p31
2      1z1hg7vb0ahhdiemnde79l
3      75fpbthrwqmzhlbjlugdc7
4      1e8pafckuyokkxphrhqw4x
...                       ...
32828  7bxnkaamr3snq1vgluvfc1
32829  5aevni09em4575077nkwhz
32830  7immqpp3q1yfuhvsdn7weo
32831  2m69mhnfq1oq6lgtxuyhgx
32832  29zwqhca3zt5nsckzqdf6c

                                              track_name      track_artist  \
0      I Dont Care with Justin Bieber  Loud Luxury Remix        ed sheeran
1                         Memories  Dillon Francis Remix          maroon 5
2                         All the Time  Don Diablo Remix      zara larsson
3                       Call You Mine  Keanu Silva Remix  the chainsmokers
4                 Someone You Loved  Future Humans Remix     lewis capaldi
...                                                  ...               ...
32828                City Of Lights  Official Radio Edit       lush  simon
32829                  Closer  Sultan  Ned Shepard Remix    tegan and sara
32830                        Sweet Surrender  Radio Edit       starkillers
32831                      Only For You  Maor Levi Remix            mat zo
32832                              Typhoon  Original Mix      julian calor

       track_popularity          track_album_id  \
0                    66  2ocs0dgtsro98gh5zsl2cx
1                    67  63rpso264urjw1x5e6cwv6
2                    70  1hosmj2elcsrr0ve9gthr4
3                    60  1nqysoef1ykkugovchbsk6
4                    69  7m7vv9wlq4i0lfujie2zsq
...                 ...                     ...
32828                42  2azrobbweeeyhqv6sb7jrt
32829                20  6kd6klxj7s8ece3abvayf5
32830                14  0ltwnsy9jgxoizo4vzuca6
32831                15  1fgrokhnhjcstl14znx8jy
32832                27  0x3muom6mhxr7pzxg95rao

                                       track_album_name  \
0      I Dont Care with Justin Bieber Loud Luxury Remix
1                         Memories Dillon Francis Remix
2                         All the Time Don Diablo Remix
3                            Call You Mine  The Remixes
4                 Someone You Loved Future Humans Remix
...                                                 ...
32828                          City Of Lights Vocal Mix
32829                                    Closer Remixed
32830                        Sweet Surrender Radio Edit
32831                              Only For You Remixes
32832                                      TyphoonStorm

      track_album_release_date   playlist_name             playlist_id  \
0                   2019-06-14       Pop Remix  37i9dqzf1dxczdd7cfekhw
1                   2019-12-13       Pop Remix  37i9dqzf1dxczdd7cfekhw
2                   2019-07-05       Pop Remix  37i9dqzf1dxczdd7cfekhw
3                   2019-07-19       Pop Remix  37i9dqzf1dxczdd7cfekhw
4                   2019-03-05       Pop Remix  37i9dqzf1dxczdd7cfekhw
...                        ...             ...                     ...
32828               2014-04-28   EDM LOVE 2020  6ji1gfr6anftt8mmtva2ux
32829               2013-03-08   EDM LOVE 2020  6ji1gfr6anftt8mmtva2ux
32830               2014-04-21   EDM LOVE 2020  6ji1gfr6anftt8mmtva2ux
32831               2014-01-01   EDM LOVE 2020  6ji1gfr6anftt8mmtva2ux
32832               2014-03-03   EDM LOVE 2020  6ji1gfr6anftt8mmtva2ux

      playlist_genre  ... loudness  mode  speechiness  acousticness  \
0                pop  ...   -2.634     1       0.0583      0.102000
1                pop  ...   -4.969     1       0.0373      0.072400
2                pop  ...   -3.432     0       0.0742      0.079400
3                pop  ...   -3.778     1       0.1020      0.028700
4                pop  ...   -4.672     1       0.0359      0.080300
...              ...  ...      ...   ...          ...           ...
32828            edm  ...   -1.814     1       0.0936      0.076600
32829            edm  ...   -4.462     1       0.0420      0.001710
32830            edm  ...   -4.899     0       0.0481      0.108000
32831            edm  ...   -3.361     1       0.1090      0.007920
32832            edm  ...   -4.571     0       0.0385      0.000133

       instrumentalness  liveness  valence    tempo  duration_ms  \
0              0.000000    0.0653   0.5180  122.036       194754
1              0.004210    0.3570   0.6930   99.972       162600
2              0.000023    0.1100   0.6130  124.008       176616
3              0.000009    0.2040   0.2770  121.956       169093
4              0.000000    0.0833   0.7250  123.976       189052
...                 ...       ...      ...      ...          ...
32828          0.000000    0.0668   0.2100  128.170       204375
32829          0.004270    0.3750   0.4000  128.041       353120
32830          0.000001    0.1500   0.4360  127.989       210112
32831          0.127000    0.3430   0.3080  128.008       367432
32832          0.341000    0.7420   0.0894  127.984       337500

       track_album_release_date_year
0                             2019.0
1                             2019.0
2                             2019.0
3                             2019.0
4                             2019.0
...                              ...
32828                         2014.0
32829                         2013.0
32830                         2014.0
32831                         2014.0
32832                         2014.0

[32833 rows x 24 columns]

In [805]:
#### A song can belong to multiple playlists. 
####Converting the 'playlist_id' column into an aggregated calculation. ( Count the number of unique playlists each track_id appears in)

In [806]:
# Count the number of unique playlists each song appears in
df['playlist_count_per_song'] = df.groupby('track_id')['playlist_id'].transform('nunique')

df.drop(columns=['playlist_id'], inplace=True) #The inplace=True parameter modifies the DataFrame directly, so you don’t need to reassign it to df.

I removed all non-alphanumeric characters from string columns to clean the text and ensure consistency for analysis and modeling.
This standardization focuses on core content, reducing noise from punctuation and symbols for better downstream processing.

In [807]:
df['duration_minutes'] = df['duration_ms'] / 60000

# Optionally, round to 2 decimal places
df['duration_minutes'] = df['duration_minutes'].round(2)

df.drop(columns=['duration_ms'], inplace=True) 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   track_id                       32833 non-null  string
 1   track_name                     32828 non-null  string
 2   track_artist                   32828 non-null  string
 3   track_popularity               32833 non-null  int64
 4   track_album_id                 32833 non-null  string
 5   track_album_name               32828 non-null  string
 6   track_album_release_date       30947 non-null  datetime64[ns]
 7   playlist_name                  32833 non-null  string
 8   playlist_genre                 32833 non-null  string
 9   playlist_subgenre              32833 non-null  string
 10  danceability                   32833 non-null  float64
 11  energy                         32833 non-null  float64
 12  key                            32833 non-null  int64
 13  loudness                       32833 non-null  float64
 14  mode                           32833 non-null  int64
 15  speechiness                    32833 non-null  float64
 16  acousticness                   32833 non-null  float64
 17  instrumentalness               32833 non-null  float64
 18  liveness                       32833 non-null  float64
 19  valence                        32833 non-null  float64
 20  tempo                          32833 non-null  float64
 21  track_album_release_date_year  30947 non-null  float64
 22  playlist_count_per_song        32833 non-null  int64
 23  duration_minutes               32833 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(4), string(8)
memory usage: 6.0 MB

I selected and printed the durations of the shortest 0.5% of songs to understand the lower range of the duration_minutes data.

This was done during EDA to check for potential data anomalies like extremely short tracks (e.g., interludes, errors) that might need filtering later.

In [808]:
# Step 1: Calculate the number of rows in the bottom 10%
num_rows = int(len(df) * 0.005)  # 10% of total rows

# Step 2: Sort by duration_minutes (ascending) and select the bottom 10%
bottom_10_df = df.nsmallest(num_rows, 'duration_minutes')

# Display results
print(bottom_10_df.duration_minutes)

11363    0.07
8339     0.49
28161    0.52
24510    0.53
28142    0.53
         ...
11633    1.56
17001    1.57
2959     1.58
5693     1.58
5694     1.58
Name: duration_minutes, Length: 164, dtype: float64

In [809]:
df['playlist_genre_count_per_song'] = df.groupby('track_id')['playlist_genre'].transform('count')
# Find the most popular genre per song (mode)
popular_genre_per_song = df.groupby('track_id')['playlist_genre'].agg(lambda x: x.mode()[0]).reset_index()
df.drop(columns=['playlist_genre'], inplace=True)

### Identify duplicate rows in the dataset

In [810]:

df = df.reset_index(drop=True)

# Now check for duplicates
duplicates = df[df.duplicated()]

# Print the duplicates or analyze the duplicates
print(duplicates)

Empty DataFrame
Columns: [track_id, track_name, track_artist, track_popularity, track_album_id, track_album_name, track_album_release_date, playlist_name, playlist_subgenre, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, track_album_release_date_year, playlist_count_per_song, duration_minutes, playlist_genre_count_per_song]
Index: []

[0 rows x 24 columns]

In [811]:
#Analyze the cause of duplicates in the dataset
print(df[df['track_id'] == '6man61jh0dzyzpwsls11jy'])

                     track_id track_name    track_artist  track_popularity  \
1339   6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
11119  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
17789  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
18767  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
19798  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
23143  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92
30248  6man61jh0dzyzpwsls11jy  Fantasias  rauw alejandro                92

               track_album_id track_album_name track_album_release_date  \
1339   1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
11119  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
17789  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
18767  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
19798  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
23143  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29
30248  1flcx9eduv7ptgm9njbmgl        Fantasias               2019-08-29

                                           playlist_name playlist_subgenre  \
1339          Pop  Pop UK  2019  Canadian Pop  2019  Pop      postteen pop
11119                                         Trap 2020               trap
17789                  LATIN POP 2020  Pop latino actual         latin pop
18767                                    Baila Reggaeton         reggaeton
19798          2020 Hits  2019  Hits  Top Global Tracks      latin hip hop
23143  Charts 2020 Top 2020Hits 2020Summer 2020Pop 20...           hip pop
30248  Charts 2020 Top 2020Hits 2020Summer 2020Pop 20...           pop edm

       danceability  ...  speechiness  acousticness  instrumentalness  \
1339          0.879  ...       0.0701         0.143               0.0
11119         0.879  ...       0.0701         0.143               0.0
17789         0.879  ...       0.0701         0.143               0.0
18767         0.879  ...       0.0701         0.143               0.0
19798         0.879  ...       0.0701         0.143               0.0
23143         0.879  ...       0.0701         0.143               0.0
30248         0.879  ...       0.0701         0.143               0.0

       liveness  valence   tempo  track_album_release_date_year  \
1339     0.0569    0.788  94.004                         2019.0
11119    0.0569    0.788  94.004                         2019.0
17789    0.0569    0.788  94.004                         2019.0
18767    0.0569    0.788  94.004                         2019.0
19798    0.0569    0.788  94.004                         2019.0
23143    0.0569    0.788  94.004                         2019.0
30248    0.0569    0.788  94.004                         2019.0

       playlist_count_per_song  duration_minutes  \
1339                         6              3.33
11119                        6              3.33
17789                        6              3.33
18767                        6              3.33
19798                        6              3.33
23143                        6              3.33
30248                        6              3.33

       playlist_genre_count_per_song
1339                               7
11119                              7
17789                              7
18767                              7
19798                              7
23143                              7
30248                              7

[7 rows x 24 columns]

In [812]:
df = df.reset_index(drop=True)

# Now check for duplicates
duplicates = df[df.duplicated()]

# Print the duplicates or analyze the duplicates
print(duplicates)

Empty DataFrame
Columns: [track_id, track_name, track_artist, track_popularity, track_album_id, track_album_name, track_album_release_date, playlist_name, playlist_subgenre, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, track_album_release_date_year, playlist_count_per_song, duration_minutes, playlist_genre_count_per_song]
Index: []

[0 rows x 24 columns]

In [813]:
# Remove all duplicate rows and keep only unique ones
df_unique = df.drop_duplicates()

# Display the unique rows
print(df_unique)

                     track_id  \
0      6f807x0ima9a1j3vpbc7vn
1      0r7cvbztwzgbtcydfa2p31
2      1z1hg7vb0ahhdiemnde79l
3      75fpbthrwqmzhlbjlugdc7
4      1e8pafckuyokkxphrhqw4x
...                       ...
32828  7bxnkaamr3snq1vgluvfc1
32829  5aevni09em4575077nkwhz
32830  7immqpp3q1yfuhvsdn7weo
32831  2m69mhnfq1oq6lgtxuyhgx
32832  29zwqhca3zt5nsckzqdf6c

                                              track_name      track_artist  \
0      I Dont Care with Justin Bieber  Loud Luxury Remix        ed sheeran
1                         Memories  Dillon Francis Remix          maroon 5
2                         All the Time  Don Diablo Remix      zara larsson
3                       Call You Mine  Keanu Silva Remix  the chainsmokers
4                 Someone You Loved  Future Humans Remix     lewis capaldi
...                                                  ...               ...
32828                City Of Lights  Official Radio Edit       lush  simon
32829                  Closer  Sultan  Ned Shepard Remix    tegan and sara
32830                        Sweet Surrender  Radio Edit       starkillers
32831                      Only For You  Maor Levi Remix            mat zo
32832                              Typhoon  Original Mix      julian calor

       track_popularity          track_album_id  \
0                    66  2ocs0dgtsro98gh5zsl2cx
1                    67  63rpso264urjw1x5e6cwv6
2                    70  1hosmj2elcsrr0ve9gthr4
3                    60  1nqysoef1ykkugovchbsk6
4                    69  7m7vv9wlq4i0lfujie2zsq
...                 ...                     ...
32828                42  2azrobbweeeyhqv6sb7jrt
32829                20  6kd6klxj7s8ece3abvayf5
32830                14  0ltwnsy9jgxoizo4vzuca6
32831                15  1fgrokhnhjcstl14znx8jy
32832                27  0x3muom6mhxr7pzxg95rao

                                       track_album_name  \
0      I Dont Care with Justin Bieber Loud Luxury Remix
1                         Memories Dillon Francis Remix
2                         All the Time Don Diablo Remix
3                            Call You Mine  The Remixes
4                 Someone You Loved Future Humans Remix
...                                                 ...
32828                          City Of Lights Vocal Mix
32829                                    Closer Remixed
32830                        Sweet Surrender Radio Edit
32831                              Only For You Remixes
32832                                      TyphoonStorm

      track_album_release_date   playlist_name          playlist_subgenre  \
0                   2019-06-14       Pop Remix                  dance pop
1                   2019-12-13       Pop Remix                  dance pop
2                   2019-07-05       Pop Remix                  dance pop
3                   2019-07-19       Pop Remix                  dance pop
4                   2019-03-05       Pop Remix                  dance pop
...                        ...             ...                        ...
32828               2014-04-28   EDM LOVE 2020  progressive electro house
32829               2013-03-08   EDM LOVE 2020  progressive electro house
32830               2014-04-21   EDM LOVE 2020  progressive electro house
32831               2014-01-01   EDM LOVE 2020  progressive electro house
32832               2014-03-03   EDM LOVE 2020  progressive electro house

       danceability  ...  speechiness  acousticness  instrumentalness  \
0             0.748  ...       0.0583      0.102000          0.000000
1             0.726  ...       0.0373      0.072400          0.004210
2             0.675  ...       0.0742      0.079400          0.000023
3             0.718  ...       0.1020      0.028700          0.000009
4             0.650  ...       0.0359      0.080300          0.000000
...             ...  ...          ...           ...               ...
32828         0.428  ...       0.0936      0.076600          0.000000
32829         0.522  ...       0.0420      0.001710          0.004270
32830         0.529  ...       0.0481      0.108000          0.000001
32831         0.626  ...       0.1090      0.007920          0.127000
32832         0.603  ...       0.0385      0.000133          0.341000

       liveness  valence    tempo  track_album_release_date_year  \
0        0.0653   0.5180  122.036                         2019.0
1        0.3570   0.6930   99.972                         2019.0
2        0.1100   0.6130  124.008                         2019.0
3        0.2040   0.2770  121.956                         2019.0
4        0.0833   0.7250  123.976                         2019.0
...         ...      ...      ...                            ...
32828    0.0668   0.2100  128.170                         2014.0
32829    0.3750   0.4000  128.041                         2013.0
32830    0.1500   0.4360  127.989                         2014.0
32831    0.3430   0.3080  128.008                         2014.0
32832    0.7420   0.0894  127.984                         2014.0

       playlist_count_per_song  duration_minutes  \
0                            2              3.25
1                            2              2.71
2                            3              2.94
3                            1              2.82
4                            1              3.15
...                        ...               ...
32828                        1              3.41
32829                        1              5.89
32830                        1              3.50
32831                        1              6.12
32832                        1              5.62

       playlist_genre_count_per_song
0                                  2
1                                  2
2                                  3
3                                  1
4                                  1
...                              ...
32828                              1
32829                              1
32830                              1
32831                              1
32832                              1

[32833 rows x 24 columns]

In [814]:
#checking
# Count the occurrences of each 'track_id'
track_count = df_unique['track_id'].value_counts()

# Filter track_ids that appear more than once
duplicate_tracks = track_count[track_count > 1]

# Display the track_ids that appear more than once
print(duplicate_tracks)

# No duplicates

track_id
7bklcz1jbubvqri2fvltvw    10
3eekarcy7kvn4yt5zfzltw     9
14sos5l36385fj3ol8hew4     9
0sf12qnh5qcw8qpgymfoqd     8
0nbxyq5txypco7pr3n8s4i     8
                          ..
0sgkqnvqo9kpytsri1h6cf     2
7busfkozrwvxsi009i3fuo     2
4enbmpgjctog5feza6rz83     2
6qhgi3mcymuwzv2glr2ahp     2
4bp0an7sxctty4kf41jxiq     2
Name: count, Length: 3166, dtype: Int64

In [815]:
df_unique.describe().T

,count,mean,min,25%,50%,75%,max,std
track_popularity,32833.0,42.477081,0.0,24.0,45.0,62.0,100.0,24.984074
track_album_release_date,30947,2012-09-09 04:27:27.668594688,1957-01-01 00:00:00,2010-12-04 00:00:00,2017-01-27 00:00:00,2019-05-16 00:00:00,2020-01-29 00:00:00,NaN
danceability,32833.0,0.65485,0.0,0.563,0.672,0.761,0.983,0.145085
energy,32833.0,0.698619,0.000175,0.581,0.721,0.84,1.0,0.18091
key,32833.0,5.374471,0.0,2.0,6.0,9.0,11.0,3.611657
loudness,32833.0,-6.719535,-46.448,-8.171,-6.166,-4.645,0.82198,2.988346
mode,32833.0,0.565711,0.0,0.0,1.0,1.0,1.0,0.495671
speechiness,32833.0,0.107068,0.0,0.041,0.0625,0.132,0.918,0.101314
acousticness,32833.0,0.175334,0.0,0.0151,0.0804,0.255,0.994,0.219633
instrumentalness,32833.0,0.084747,0.0,0.0,0.000016,0.00483,0.994,0.22423
liveness,32833.0,0.190176,0.0,0.0927,0.127,0.248,0.996,0.154317
valence,32833.0,0.510561,0.0,0.331,0.512,0.693,0.991,0.233146
tempo,32833.0,120.881132,0.0,99.96,121.984,133.918,239.44,26.903624
track_album_release_date_year,30947.0,2012.200536,1957.0,2010.0,2017.0,2019.0,2020.0,10.397763
playlist_count_per_song,32833.0,1.356044,1.0,1.0,1.0,1.0,8.0,0.860129
duration_minutes,32833.0,3.763335,0.07,3.13,3.6,4.23,8.63,0.99724
playlist_genre_count_per_song,32833.0,1.413304,1.0,1.0,1.0,1.0,10.0,0.995963

### Transferring columns to another dataframe following a similar meaning in other column

In [833]:
df_text = df[['track_id', 'track_name', 'track_album_name', 'playlist_name']]

# Save the DataFrame properly
with open("spotify_songs_df_text.pkl", "wb") as f:
    pickle.dump(df_text, f)

In [838]:
df_unique=df.drop(columns=['track_name','track_album_name','playlist_name','playlist_subgenre'])

#playlist_subgenre - NO NEED

In [839]:
df_final_unique = df_unique.drop_duplicates(subset=['track_id'], keep='first')
df_final_unique.info() # Verify shape and counts

<class 'pandas.core.frame.DataFrame'>
Index: 28356 entries, 0 to 32832
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   track_id                       28356 non-null  string
 1   track_artist                   28352 non-null  string
 2   track_popularity               28356 non-null  int64
 3   track_album_id                 28356 non-null  string
 4   track_album_release_date       26675 non-null  datetime64[ns]
 5   danceability                   28356 non-null  float64
 6   energy                         28356 non-null  float64
 7   key                            28356 non-null  int64
 8   loudness                       28356 non-null  float64
 9   mode                           28356 non-null  int64
 10  speechiness                    28356 non-null  float64
 11  acousticness                   28356 non-null  float64
 12  instrumentalness               28356 non-null  float64
 13  liveness                       28356 non-null  float64
 14  valence                        28356 non-null  float64
 15  tempo                          28356 non-null  float64
 16  track_album_release_date_year  26675 non-null  float64
 17  playlist_count_per_song        28356 non-null  int64
 18  duration_minutes               28356 non-null  float64
 19  playlist_genre_count_per_song  28356 non-null  int64
dtypes: datetime64[ns](1), float64(11), int64(5), string(3)
memory usage: 4.5 MB

In [840]:
## Saving to Pickle

import pickle

# Specify the filename
filename = 'spotify_songs_df_after_data_prep_10.3.25.pkl'

# Save DataFrame to a pickle file
df_final_unique.to_pickle(filename)

# Load DataFrame from a pickle file
df_final_unique = pd.read_pickle(filename)

In [841]:
df_sorted = df_final_unique.sort_values(by='track_id', ascending=False)

# Save the sorted DataFrame to a CSV file
df_sorted.to_csv('sorted_spotify_songs_data.csv', index=False)